// <auto-generated />
using System;
using LM.MSEmail.Api.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LM.MSEmail.Api.Infra.Migrations
{
    [DbContext(typeof(EmailContext))]
    [Migration("20200510061110_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LM.MSEmail.Api.Domain.Models.History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResponseStatusCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TemplateData")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TemplateId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("History");
                });

            modelBuilder.Entity("LM.MSEmail.Api.Domain.Models.History", b =>
                {
                    b.OwnsOne("LM.MSEmail.Api.Domain.Valuables.EmailFrom", "From", b1 =>
                        {
                            b1.Property<long>("HistoryId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Email")
                                .HasColumnName("From_Email")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Name")
                                .HasColumnName("From_Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("HistoryId");

                            b1.ToTable("History");

                            b1.WithOwner()
                                .HasForeignKey("HistoryId");
                        });

                    b.OwnsOne("LM.MSEmail.Api.Domain.Valuables.EmailTo", "To", b1 =>
                        {
                            b1.Property<long>("HistoryId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Email")
                                .HasColumnName("To_Email")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Name")
                                .HasColumnName("To_Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("HistoryId");

                            b1.ToTable("History");

                            b1.WithOwner()
                                .HasForeignKey("HistoryId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
